### ISSUE TITLE
Javascript console error when adding image

### ISSUE THREAD

**Issue by pboyer84** [joshpc/RecordVault-Issues#23]
**Describe the bug**
The Add Image feature is not working right now.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Reflector article.
2. Click on the circle button to add an image and select an image. I tested with png jpg and gif. All same results.
3. Observe that the article stays the same.
4. Hit F12 and notice that a new entry appears in the javascript console.

**Expected behaviour**
The image that I selected from the File Select dialog should appear in the article at the caret position I selected.

**Screenshots**
Console error on Chrome:
![image](https://user-images.githubusercontent.com/1923614/52545350-d4c31b00-2d84-11e9-8142-8c1d013dead5.png)

Console error on Edge:
![image](https://user-images.githubusercontent.com/1923614/52545358-e1e00a00-2d84-11e9-83d0-ce0ea41d8050.png)

**Browser and Device (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Edge
 - Version, Chrome 71.0.3578.98 (Official Build) (64-bit),
                 Microsoft Edge 42.17134.1.0

**Additional context**
This used to work. One of the last images I remember uploading successfully was for the Lune article in Freeport. Hope that helps narrow down a point in time before something changes.

**Comment by joshpc** [comment]
@pboyer84 thanks -- Fix is being deployed now!
